name: Automated Testing

permissions:
  actions: write

defaults:
  run:
    shell: bash

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    # sorry crystalflame :3
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ffrostfall/crunchyroll

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.0

      - name: Run tests
        run: lune run test
